DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  FRAME_SAMPLING: 'like omnivore'
  USE_RAND_AUGMENT: True
MODEL:
  ARCH: omnivore_swinB
  MODEL_NAME: Omnivore
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  DATASET: ave
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1
  NUM_FEATURES: 2
  FEATURE_EXTRACTION: True
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
AVE:
  VISUAL_DATA_DIR: "/mnt/2Tkioxia/yu/feats_psp_by_video_frame/train"
  TEST_LIST: /home/server-05/YU/OGM-GE_CVPR2022/TIM-main/annotations/annotations/AVE/AVE_1_second_train_feature_times.pkl
NUM_GPUS: 1     # ✓✓✓✓✓✓
OUTPUT_DIR: /mnt/2Tkioxia/yu/feats_ominvore/train  # ✓✓✓✓✓✓
