DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  FRAME_SAMPLING: 'like omnivore'
  USE_RAND_AUGMENT: True
MODEL:
  ARCH: omnivore_swinB_epic
  MODEL_NAME: Omnivore
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  DATASET: epickitchens
  BATCH_SIZE: 4
  NUM_SPATIAL_CROPS: 1
  NUM_FEATURES: 1
  FEATURE_EXTRACTION: True
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1     # ✓✓✓✓✓✓
OUTPUT_DIR: output   # ✓✓✓✓✓✓
